checkoutLocation: "go/src/github.com/jrbeverly/cobra-cmd-with-docs"
workspaceLocation: "go/src/github.com/jrbeverly/cobra-cmd-with-docs"

github:
    prebuilds:
        pullRequestsFromForks: true
image:
  file: .gitpod/Dockerfile

vscode:
  extensions:
    - golang.go
    - ms-azuretools.vscode-docker
    - bazelbuild.vscode-bazel

